# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qrCodeGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IssuePayment(object):
    def setupUi(self, IssuePayment):
        IssuePayment.setObjectName("IssuePayment")
        IssuePayment.resize(453, 415)
        IssuePayment.setStyleSheet("background-color: rgb(22, 25, 29);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(IssuePayment)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qrCodeWidget = QtWidgets.QWidget(IssuePayment)
        self.qrCodeWidget.setObjectName("qrCodeWidget")
        self.verticalLayout.addWidget(self.qrCodeWidget)
        self.widget_2 = QtWidgets.QWidget(IssuePayment)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.confirmPaymentBtn = QtWidgets.QPushButton(self.widget_2)
        self.confirmPaymentBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.confirmPaymentBtn.setFont(font)
        self.confirmPaymentBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmPaymentBtn.setStyleSheet("background-color: rgb(31, 35, 42);")
        self.confirmPaymentBtn.setObjectName("confirmPaymentBtn")
        self.verticalLayout_2.addWidget(self.confirmPaymentBtn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(IssuePayment)
        QtCore.QMetaObject.connectSlotsByName(IssuePayment)

    def retranslateUi(self, IssuePayment):
        _translate = QtCore.QCoreApplication.translate
        IssuePayment.setWindowTitle(_translate("IssuePayment", "Dialog"))
        self.label.setText(_translate("IssuePayment", "<html><head/><body><p>1. Scan the QR Code to proceed </p><p>2. Select the link and complete payment</p><p>3. Select the Confirm Payment Button on completion</p></body></html>"))
        self.confirmPaymentBtn.setText(_translate("IssuePayment", "CONFIRM PAYMENT"))
