# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\receiptItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 31)
        Form.setMaximumSize(QtCore.QSize(16777215, 31))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 5, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.item_name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.item_name.setFont(font)
        self.item_name.setObjectName("item_name")
        self.horizontalLayout.addWidget(self.item_name)
        self.item_qty = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.item_qty.setFont(font)
        self.item_qty.setObjectName("item_qty")
        self.horizontalLayout.addWidget(self.item_qty, 0, QtCore.Qt.AlignLeft)
        self.item_cost = QtWidgets.QLabel(Form)
        self.item_cost.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.item_cost.setFont(font)
        self.item_cost.setObjectName("item_cost")
        self.horizontalLayout.addWidget(self.item_cost)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.item_name.setText(_translate("Form", "Item_name"))
        self.item_qty.setText(_translate("Form", "Quantity_Number"))
        self.item_cost.setText(_translate("Form", "Cost"))
